package com.orm;
// Generated 2011-11-22 22:11:41 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Reply generated by hbm2java
 */
public class Reply  implements java.io.Serializable {


     private Integer id;
     private Admin admin;
     private Student student;
     private Post post;
     private String content;
     private Date publishTime;

    public Reply() {
    }

	
    public Reply(Post post, String content) {
        this.post = post;
        this.content = content;
    }
    public Reply(Admin admin, Student student, Post post, String content, Date publishTime) {
       this.admin = admin;
       this.student = student;
       this.post = post;
       this.content = content;
       this.publishTime = publishTime;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Admin getAdmin() {
        return this.admin;
    }
    
    public void setAdmin(Admin admin) {
        this.admin = admin;
    }
    public Student getStudent() {
        return this.student;
    }
    
    public void setStudent(Student student) {
        this.student = student;
    }
    public Post getPost() {
        return this.post;
    }
    
    public void setPost(Post post) {
        this.post = post;
    }
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }
    public Date getPublishTime() {
        return this.publishTime;
    }
    
    public void setPublishTime(Date publishTime) {
        this.publishTime = publishTime;
    }




}


